package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SiActaDesecho generated by hbm2java
 */
@Entity
@Table(name="SI_ACTA_DESECHO"
    ,schema="dbo"
    ,catalog="DB_GRUPO4"
)
public class SiActaDesecho  implements java.io.Serializable {


     private SiActaDesechoId id;
     private SiDesecho siDesecho;
     private SiPersona siPersonaByCedula1;
     private SiPersona siPersonaByCedula2;
     private Date fechaDesecho;
     private Set<SiSubinformeDesecho> siSubinformeDesechos = new HashSet<SiSubinformeDesecho>(0);

    public SiActaDesecho() {
    }

	
    public SiActaDesecho(SiActaDesechoId id, SiDesecho siDesecho, SiPersona siPersonaByCedula1, SiPersona siPersonaByCedula2, Date fechaDesecho) {
        this.id = id;
        this.siDesecho = siDesecho;
        this.siPersonaByCedula1 = siPersonaByCedula1;
        this.siPersonaByCedula2 = siPersonaByCedula2;
        this.fechaDesecho = fechaDesecho;
    }
    public SiActaDesecho(SiActaDesechoId id, SiDesecho siDesecho, SiPersona siPersonaByCedula1, SiPersona siPersonaByCedula2, Date fechaDesecho, Set<SiSubinformeDesecho> siSubinformeDesechos) {
       this.id = id;
       this.siDesecho = siDesecho;
       this.siPersonaByCedula1 = siPersonaByCedula1;
       this.siPersonaByCedula2 = siPersonaByCedula2;
       this.fechaDesecho = fechaDesecho;
       this.siSubinformeDesechos = siSubinformeDesechos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="numero", column=@Column(name="NUMERO", nullable=false) ), 
        @AttributeOverride(name="anno", column=@Column(name="ANNO", nullable=false) ), 
        @AttributeOverride(name="oficioDesecho", column=@Column(name="OFICIO_DESECHO", nullable=false, length=30) ) } )
    public SiActaDesechoId getId() {
        return this.id;
    }
    
    public void setId(SiActaDesechoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="NUMERO", referencedColumnName="NUMERO", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ANNO", referencedColumnName="ANNO", nullable=false, insertable=false, updatable=false) } )
    public SiDesecho getSiDesecho() {
        return this.siDesecho;
    }
    
    public void setSiDesecho(SiDesecho siDesecho) {
        this.siDesecho = siDesecho;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CEDULA1", nullable=false)
    public SiPersona getSiPersonaByCedula1() {
        return this.siPersonaByCedula1;
    }
    
    public void setSiPersonaByCedula1(SiPersona siPersonaByCedula1) {
        this.siPersonaByCedula1 = siPersonaByCedula1;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CEDULA2", nullable=false)
    public SiPersona getSiPersonaByCedula2() {
        return this.siPersonaByCedula2;
    }
    
    public void setSiPersonaByCedula2(SiPersona siPersonaByCedula2) {
        this.siPersonaByCedula2 = siPersonaByCedula2;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_DESECHO", nullable=false, length=10)
    public Date getFechaDesecho() {
        return this.fechaDesecho;
    }
    
    public void setFechaDesecho(Date fechaDesecho) {
        this.fechaDesecho = fechaDesecho;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="siActaDesecho")
    public Set<SiSubinformeDesecho> getSiSubinformeDesechos() {
        return this.siSubinformeDesechos;
    }
    
    public void setSiSubinformeDesechos(Set<SiSubinformeDesecho> siSubinformeDesechos) {
        this.siSubinformeDesechos = siSubinformeDesechos;
    }




}


