package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SiActaDesechoId generated by hbm2java
 */
@Embeddable
public class SiActaDesechoId  implements java.io.Serializable {


     private int numero;
     private int anno;
     private String oficioDesecho;

    public SiActaDesechoId() {
    }

    public SiActaDesechoId(int numero, int anno, String oficioDesecho) {
       this.numero = numero;
       this.anno = anno;
       this.oficioDesecho = oficioDesecho;
    }
   


    @Column(name="NUMERO", nullable=false)
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }


    @Column(name="ANNO", nullable=false)
    public int getAnno() {
        return this.anno;
    }
    
    public void setAnno(int anno) {
        this.anno = anno;
    }


    @Column(name="OFICIO_DESECHO", nullable=false, length=30)
    public String getOficioDesecho() {
        return this.oficioDesecho;
    }
    
    public void setOficioDesecho(String oficioDesecho) {
        this.oficioDesecho = oficioDesecho;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SiActaDesechoId) ) return false;
		 SiActaDesechoId castOther = ( SiActaDesechoId ) other; 
         
		 return (this.getNumero()==castOther.getNumero())
 && (this.getAnno()==castOther.getAnno())
 && ( (this.getOficioDesecho()==castOther.getOficioDesecho()) || ( this.getOficioDesecho()!=null && castOther.getOficioDesecho()!=null && this.getOficioDesecho().equals(castOther.getOficioDesecho()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNumero();
         result = 37 * result + this.getAnno();
         result = 37 * result + ( getOficioDesecho() == null ? 0 : this.getOficioDesecho().hashCode() );
         return result;
   }   


}


