package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * SiAdquisicionPorTraslado generated by hbm2java
 */
@Entity
@Table(name="SI_ADQUISICION_POR_TRASLADO"
    ,schema="dbo"
    ,catalog="DB_GRUPO4"
)
public class SiAdquisicionPorTraslado  implements java.io.Serializable {


     private int id;
     private SiAdquisicion siAdquisicion;
     private SiPersona siPersona;
     private SiUnidadAcademica siUnidadAcademica;
     private String numeroOficio;
     private byte[] reporte;

    public SiAdquisicionPorTraslado() {
    }

	
    public SiAdquisicionPorTraslado(SiAdquisicion siAdquisicion, SiPersona siPersona, SiUnidadAcademica siUnidadAcademica, String numeroOficio) {
        this.siAdquisicion = siAdquisicion;
        this.siPersona = siPersona;
        this.siUnidadAcademica = siUnidadAcademica;
        this.numeroOficio = numeroOficio;
    }
    public SiAdquisicionPorTraslado(SiAdquisicion siAdquisicion, SiPersona siPersona, SiUnidadAcademica siUnidadAcademica, String numeroOficio, byte[] reporte) {
       this.siAdquisicion = siAdquisicion;
       this.siPersona = siPersona;
       this.siUnidadAcademica = siUnidadAcademica;
       this.numeroOficio = numeroOficio;
       this.reporte = reporte;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="siAdquisicion"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public SiAdquisicion getSiAdquisicion() {
        return this.siAdquisicion;
    }
    
    public void setSiAdquisicion(SiAdquisicion siAdquisicion) {
        this.siAdquisicion = siAdquisicion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CEDULA", nullable=false)
    public SiPersona getSiPersona() {
        return this.siPersona;
    }
    
    public void setSiPersona(SiPersona siPersona) {
        this.siPersona = siPersona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODIGO", nullable=false)
    public SiUnidadAcademica getSiUnidadAcademica() {
        return this.siUnidadAcademica;
    }
    
    public void setSiUnidadAcademica(SiUnidadAcademica siUnidadAcademica) {
        this.siUnidadAcademica = siUnidadAcademica;
    }

    
    @Column(name="NUMERO_OFICIO", nullable=false, length=30)
    public String getNumeroOficio() {
        return this.numeroOficio;
    }
    
    public void setNumeroOficio(String numeroOficio) {
        this.numeroOficio = numeroOficio;
    }

    
    @Column(name="REPORTE")
    public byte[] getReporte() {
        return this.reporte;
    }
    
    public void setReporte(byte[] reporte) {
        this.reporte = reporte;
    }




}


