package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SiAdquisicion generated by hbm2java
 */
@Entity
@Table(name="SI_ADQUISICION"
    ,schema="dbo"
    ,catalog="DB_GRUPO4"
)
public class SiAdquisicion  implements java.io.Serializable {


     private int id;
     private Date fechaAdquisicion;
     private SiPresupuestoOrdinario siPresupuestoOrdinario;
     private Set<SiBienInstitucional> siBienInstitucionals = new HashSet<SiBienInstitucional>(0);
     private SiAdquisicionPorTraslado siAdquisicionPorTraslado;
     private SiOficinaSuministros siOficinaSuministros;
     private SiFundacionUcr siFundacionUcr;

    public SiAdquisicion() {
    }

	
    public SiAdquisicion(int id, Date fechaAdquisicion) {
        this.id = id;
        this.fechaAdquisicion = fechaAdquisicion;
    }
    public SiAdquisicion(int id, Date fechaAdquisicion, SiPresupuestoOrdinario siPresupuestoOrdinario, Set<SiBienInstitucional> siBienInstitucionals, SiAdquisicionPorTraslado siAdquisicionPorTraslado, SiOficinaSuministros siOficinaSuministros, SiFundacionUcr siFundacionUcr) {
       this.id = id;
       this.fechaAdquisicion = fechaAdquisicion;
       this.siPresupuestoOrdinario = siPresupuestoOrdinario;
       this.siBienInstitucionals = siBienInstitucionals;
       this.siAdquisicionPorTraslado = siAdquisicionPorTraslado;
       this.siOficinaSuministros = siOficinaSuministros;
       this.siFundacionUcr = siFundacionUcr;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ADQUISICION", nullable=false, length=10)
    public Date getFechaAdquisicion() {
        return this.fechaAdquisicion;
    }
    
    public void setFechaAdquisicion(Date fechaAdquisicion) {
        this.fechaAdquisicion = fechaAdquisicion;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="siAdquisicion")
    public SiPresupuestoOrdinario getSiPresupuestoOrdinario() {
        return this.siPresupuestoOrdinario;
    }
    
    public void setSiPresupuestoOrdinario(SiPresupuestoOrdinario siPresupuestoOrdinario) {
        this.siPresupuestoOrdinario = siPresupuestoOrdinario;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="siAdquisicions")
    public Set<SiBienInstitucional> getSiBienInstitucionals() {
        return this.siBienInstitucionals;
    }
    
    public void setSiBienInstitucionals(Set<SiBienInstitucional> siBienInstitucionals) {
        this.siBienInstitucionals = siBienInstitucionals;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="siAdquisicion")
    public SiAdquisicionPorTraslado getSiAdquisicionPorTraslado() {
        return this.siAdquisicionPorTraslado;
    }
    
    public void setSiAdquisicionPorTraslado(SiAdquisicionPorTraslado siAdquisicionPorTraslado) {
        this.siAdquisicionPorTraslado = siAdquisicionPorTraslado;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="siAdquisicion")
    public SiOficinaSuministros getSiOficinaSuministros() {
        return this.siOficinaSuministros;
    }
    
    public void setSiOficinaSuministros(SiOficinaSuministros siOficinaSuministros) {
        this.siOficinaSuministros = siOficinaSuministros;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="siAdquisicion")
    public SiFundacionUcr getSiFundacionUcr() {
        return this.siFundacionUcr;
    }
    
    public void setSiFundacionUcr(SiFundacionUcr siFundacionUcr) {
        this.siFundacionUcr = siFundacionUcr;
    }




}


