package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SiDesecho generated by hbm2java
 */
@Entity
@Table(name="SI_DESECHO"
    ,schema="dbo"
    ,catalog="DB_GRUPO4"
)
public class SiDesecho  implements java.io.Serializable {


     private SiDesechoId id;
     private Date fechaSolicitud;
     private String estado;
     private Set<SiActaDesecho> siActaDesechos = new HashSet<SiActaDesecho>(0);
     private Set<SiInformeTecnico> siInformeTecnicos = new HashSet<SiInformeTecnico>(0);
     private Set<SiSolicitudDesecho> siSolicitudDesechos = new HashSet<SiSolicitudDesecho>(0);

    public SiDesecho() {
    }

	
    public SiDesecho(SiDesechoId id, Date fechaSolicitud, String estado) {
        this.id = id;
        this.fechaSolicitud = fechaSolicitud;
        this.estado = estado;
    }
    public SiDesecho(SiDesechoId id, Date fechaSolicitud, String estado, Set<SiActaDesecho> siActaDesechos, Set<SiInformeTecnico> siInformeTecnicos, Set<SiSolicitudDesecho> siSolicitudDesechos) {
       this.id = id;
       this.fechaSolicitud = fechaSolicitud;
       this.estado = estado;
       this.siActaDesechos = siActaDesechos;
       this.siInformeTecnicos = siInformeTecnicos;
       this.siSolicitudDesechos = siSolicitudDesechos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="numero", column=@Column(name="NUMERO", nullable=false) ), 
        @AttributeOverride(name="anno", column=@Column(name="ANNO", nullable=false) ) } )
    public SiDesechoId getId() {
        return this.id;
    }
    
    public void setId(SiDesechoId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_SOLICITUD", nullable=false, length=10)
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }

    
    @Column(name="ESTADO", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="siDesecho")
    public Set<SiActaDesecho> getSiActaDesechos() {
        return this.siActaDesechos;
    }
    
    public void setSiActaDesechos(Set<SiActaDesecho> siActaDesechos) {
        this.siActaDesechos = siActaDesechos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="siDesecho")
    public Set<SiInformeTecnico> getSiInformeTecnicos() {
        return this.siInformeTecnicos;
    }
    
    public void setSiInformeTecnicos(Set<SiInformeTecnico> siInformeTecnicos) {
        this.siInformeTecnicos = siInformeTecnicos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="siDesecho")
    public Set<SiSolicitudDesecho> getSiSolicitudDesechos() {
        return this.siSolicitudDesechos;
    }
    
    public void setSiSolicitudDesechos(Set<SiSolicitudDesecho> siSolicitudDesechos) {
        this.siSolicitudDesechos = siSolicitudDesechos;
    }




}


