package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SiInformeTecnicoId generated by hbm2java
 */
@Embeddable
public class SiInformeTecnicoId  implements java.io.Serializable {


     private int numeroInforme;
     private int annoInforme;

    public SiInformeTecnicoId() {
    }

    public SiInformeTecnicoId(int numeroInforme, int annoInforme) {
       this.numeroInforme = numeroInforme;
       this.annoInforme = annoInforme;
    }
   


    @Column(name="NUMERO_INFORME", nullable=false)
    public int getNumeroInforme() {
        return this.numeroInforme;
    }
    
    public void setNumeroInforme(int numeroInforme) {
        this.numeroInforme = numeroInforme;
    }


    @Column(name="ANNO_INFORME", nullable=false)
    public int getAnnoInforme() {
        return this.annoInforme;
    }
    
    public void setAnnoInforme(int annoInforme) {
        this.annoInforme = annoInforme;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SiInformeTecnicoId) ) return false;
		 SiInformeTecnicoId castOther = ( SiInformeTecnicoId ) other; 
         
		 return (this.getNumeroInforme()==castOther.getNumeroInforme())
 && (this.getAnnoInforme()==castOther.getAnnoInforme());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNumeroInforme();
         result = 37 * result + this.getAnnoInforme();
         return result;
   }   


}


