package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SiInformeTecnico generated by hbm2java
 */
@Entity
@Table(name="SI_INFORME_TECNICO"
    ,schema="dbo"
    ,catalog="DB_GRUPO4"
)
public class SiInformeTecnico  implements java.io.Serializable {


     private SiInformeTecnicoId id;
     private SiDesecho siDesecho;
     private String motivoGeneral;
     private String recomendacion;
     private Set<SiSubinformeDesecho> siSubinformeDesechos = new HashSet<SiSubinformeDesecho>(0);

    public SiInformeTecnico() {
    }

	
    public SiInformeTecnico(SiInformeTecnicoId id, SiDesecho siDesecho) {
        this.id = id;
        this.siDesecho = siDesecho;
    }
    public SiInformeTecnico(SiInformeTecnicoId id, SiDesecho siDesecho, String motivoGeneral, String recomendacion, Set<SiSubinformeDesecho> siSubinformeDesechos) {
       this.id = id;
       this.siDesecho = siDesecho;
       this.motivoGeneral = motivoGeneral;
       this.recomendacion = recomendacion;
       this.siSubinformeDesechos = siSubinformeDesechos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="numeroInforme", column=@Column(name="NUMERO_INFORME", nullable=false) ), 
        @AttributeOverride(name="annoInforme", column=@Column(name="ANNO_INFORME", nullable=false) ) } )
    public SiInformeTecnicoId getId() {
        return this.id;
    }
    
    public void setId(SiInformeTecnicoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="NUMERO", referencedColumnName="NUMERO", nullable=false), 
        @JoinColumn(name="ANNO", referencedColumnName="ANNO", nullable=false) } )
    public SiDesecho getSiDesecho() {
        return this.siDesecho;
    }
    
    public void setSiDesecho(SiDesecho siDesecho) {
        this.siDesecho = siDesecho;
    }

    
    @Column(name="MOTIVO_GENERAL", length=20)
    public String getMotivoGeneral() {
        return this.motivoGeneral;
    }
    
    public void setMotivoGeneral(String motivoGeneral) {
        this.motivoGeneral = motivoGeneral;
    }

    
    @Column(name="RECOMENDACION", length=300)
    public String getRecomendacion() {
        return this.recomendacion;
    }
    
    public void setRecomendacion(String recomendacion) {
        this.recomendacion = recomendacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="siInformeTecnico")
    public Set<SiSubinformeDesecho> getSiSubinformeDesechos() {
        return this.siSubinformeDesechos;
    }
    
    public void setSiSubinformeDesechos(Set<SiSubinformeDesecho> siSubinformeDesechos) {
        this.siSubinformeDesechos = siSubinformeDesechos;
    }




}


