package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * SiOficinaSuministros generated by hbm2java
 */
@Entity
@Table(name="SI_OFICINA_SUMINISTROS"
    ,schema="dbo"
    ,catalog="DB_GRUPO4"
)
public class SiOficinaSuministros  implements java.io.Serializable {


     private int id;
     private SiAdquisicion siAdquisicion;
     private String empresa;
     private String ordenCompra;
     private String numeroContratacion;

    public SiOficinaSuministros() {
    }

    public SiOficinaSuministros(SiAdquisicion siAdquisicion, String empresa, String ordenCompra, String numeroContratacion) {
       this.siAdquisicion = siAdquisicion;
       this.empresa = empresa;
       this.ordenCompra = ordenCompra;
       this.numeroContratacion = numeroContratacion;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="siAdquisicion"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public SiAdquisicion getSiAdquisicion() {
        return this.siAdquisicion;
    }
    
    public void setSiAdquisicion(SiAdquisicion siAdquisicion) {
        this.siAdquisicion = siAdquisicion;
    }

    
    @Column(name="EMPRESA", nullable=false, length=100)
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="ORDEN_COMPRA", nullable=false, length=50)
    public String getOrdenCompra() {
        return this.ordenCompra;
    }
    
    public void setOrdenCompra(String ordenCompra) {
        this.ordenCompra = ordenCompra;
    }

    
    @Column(name="NUMERO_CONTRATACION", nullable=false, length=50)
    public String getNumeroContratacion() {
        return this.numeroContratacion;
    }
    
    public void setNumeroContratacion(String numeroContratacion) {
        this.numeroContratacion = numeroContratacion;
    }




}


