package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SiPersona generated by hbm2java
 */
@Entity
@Table(name = "SI_PERSONA",
         schema = "dbo",
         catalog = "DB_GRUPO4"
)
public class SiPersona implements java.io.Serializable {

    private String cedula;
    private String nombre;
    private String primerApellido;
    private String segundoApellido;
    private boolean funcionarioInie;
    private Set<SiBienInstitucional> siBienInstitucionals = new HashSet<SiBienInstitucional>(0);
    private Set<SiPrestamo> siPrestamos = new HashSet<SiPrestamo>(0);
    private Set<SiActaDesecho> siActaDesechosForCedula1 = new HashSet<SiActaDesecho>(0);
    private Set<SiAdquisicionPorTraslado> siAdquisicionPorTraslados = new HashSet<SiAdquisicionPorTraslado>(0);
    private Set<SiActaDesecho> siActaDesechosForCedula2 = new HashSet<SiActaDesecho>(0);
    private Set<SiUnidadEvaluadora> siUnidadEvaluadoras = new HashSet<SiUnidadEvaluadora>(0);
    private Set<SiTraslado> siTraslados = new HashSet<SiTraslado>(0);

    public SiPersona() {
    }

    public SiPersona(String cedula, String nombre, String primerApellido, boolean funcionarioInie) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.primerApellido = primerApellido;
        this.funcionarioInie = funcionarioInie;
    }

    public SiPersona(String cedula, String nombre, String primerApellido, String segundoApellido, boolean funcionarioInie, Set<SiBienInstitucional> siBienInstitucionals, Set<SiPrestamo> siPrestamos, Set<SiActaDesecho> siActaDesechosForCedula1, Set<SiAdquisicionPorTraslado> siAdquisicionPorTraslados, Set<SiActaDesecho> siActaDesechosForCedula2, Set<SiUnidadEvaluadora> siUnidadEvaluadoras, Set<SiTraslado> siTraslados) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.primerApellido = primerApellido;
        this.segundoApellido = segundoApellido;
        this.funcionarioInie = funcionarioInie;
        this.siBienInstitucionals = siBienInstitucionals;
        this.siPrestamos = siPrestamos;
        this.siActaDesechosForCedula1 = siActaDesechosForCedula1;
        this.siAdquisicionPorTraslados = siAdquisicionPorTraslados;
        this.siActaDesechosForCedula2 = siActaDesechosForCedula2;
        this.siUnidadEvaluadoras = siUnidadEvaluadoras;
        this.siTraslados = siTraslados;
    }

    @Id

    @Column(name = "CEDULA", unique = true, nullable = false, length = 15)
    public String getCedula() {
        return this.cedula;
    }

    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    @Column(name = "NOMBRE", nullable = false, length = 20)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "PRIMER_APELLIDO", nullable = false, length = 30)
    public String getPrimerApellido() {
        return this.primerApellido;
    }

    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }

    @Column(name = "SEGUNDO_APELLIDO", length = 30)
    public String getSegundoApellido() {
        return this.segundoApellido;
    }

    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }

    @Column(name = "FUNCIONARIO_INIE", nullable = false)
    public boolean isFuncionarioInie() {
        return this.funcionarioInie;
    }

    public void setFuncionarioInie(boolean funcionarioInie) {
        this.funcionarioInie = funcionarioInie;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "siPersona")
    public Set<SiBienInstitucional> getSiBienInstitucionals() {
        return this.siBienInstitucionals;
    }

    public void setSiBienInstitucionals(Set<SiBienInstitucional> siBienInstitucionals) {
        this.siBienInstitucionals = siBienInstitucionals;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "siPersona")
    public Set<SiPrestamo> getSiPrestamos() {
        return this.siPrestamos;
    }

    public void setSiPrestamos(Set<SiPrestamo> siPrestamos) {
        this.siPrestamos = siPrestamos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "siPersonaByCedula1")
    public Set<SiActaDesecho> getSiActaDesechosForCedula1() {
        return this.siActaDesechosForCedula1;
    }

    public void setSiActaDesechosForCedula1(Set<SiActaDesecho> siActaDesechosForCedula1) {
        this.siActaDesechosForCedula1 = siActaDesechosForCedula1;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "siPersona")
    public Set<SiAdquisicionPorTraslado> getSiAdquisicionPorTraslados() {
        return this.siAdquisicionPorTraslados;
    }

    public void setSiAdquisicionPorTraslados(Set<SiAdquisicionPorTraslado> siAdquisicionPorTraslados) {
        this.siAdquisicionPorTraslados = siAdquisicionPorTraslados;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "siPersonaByCedula2")
    public Set<SiActaDesecho> getSiActaDesechosForCedula2() {
        return this.siActaDesechosForCedula2;
    }

    public void setSiActaDesechosForCedula2(Set<SiActaDesecho> siActaDesechosForCedula2) {
        this.siActaDesechosForCedula2 = siActaDesechosForCedula2;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "siPersona")
    public Set<SiUnidadEvaluadora> getSiUnidadEvaluadoras() {
        return this.siUnidadEvaluadoras;
    }

    public void setSiUnidadEvaluadoras(Set<SiUnidadEvaluadora> siUnidadEvaluadoras) {
        this.siUnidadEvaluadoras = siUnidadEvaluadoras;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "siPersona")
    public Set<SiTraslado> getSiTraslados() {
        return this.siTraslados;
    }

    public void setSiTraslados(Set<SiTraslado> siTraslados) {
        this.siTraslados = siTraslados;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (cedula != null ? cedula.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        if (!(object instanceof SiPersona)) {
            return false;
        }
        SiPersona other = (SiPersona) object;
        if ((this.cedula == null && other.cedula != null) || (this.cedula != null && !this.cedula.equals(other.cedula))) {
            return false;
        }
        return true;
    }

}
