package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SiSeTraslada generated by hbm2java
 */
@Entity
@Table(name="SI_SE_TRASLADA"
    ,schema="dbo"
    ,catalog="DB_GRUPO4"
)
public class SiSeTraslada  implements java.io.Serializable {


     private SiSeTrasladaId id;
     private SiBienInstitucional siBienInstitucional;
     private SiTraslado siTraslado;
     private SiUnidadAcademica siUnidadAcademica;

    public SiSeTraslada() {
    }

    public SiSeTraslada(SiSeTrasladaId id, SiBienInstitucional siBienInstitucional, SiTraslado siTraslado, SiUnidadAcademica siUnidadAcademica) {
       this.id = id;
       this.siBienInstitucional = siBienInstitucional;
       this.siTraslado = siTraslado;
       this.siUnidadAcademica = siUnidadAcademica;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="numero", column=@Column(name="NUMERO", nullable=false) ), 
        @AttributeOverride(name="anno", column=@Column(name="ANNO", nullable=false) ), 
        @AttributeOverride(name="codigo", column=@Column(name="CODIGO", nullable=false, length=20) ), 
        @AttributeOverride(name="consecutivo", column=@Column(name="CONSECUTIVO", nullable=false) ) } )
    public SiSeTrasladaId getId() {
        return this.id;
    }
    
    public void setId(SiSeTrasladaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONSECUTIVO", nullable=false, insertable=false, updatable=false)
    public SiBienInstitucional getSiBienInstitucional() {
        return this.siBienInstitucional;
    }
    
    public void setSiBienInstitucional(SiBienInstitucional siBienInstitucional) {
        this.siBienInstitucional = siBienInstitucional;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="NUMERO", referencedColumnName="NUMERO", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ANNO", referencedColumnName="ANNO", nullable=false, insertable=false, updatable=false) } )
    public SiTraslado getSiTraslado() {
        return this.siTraslado;
    }
    
    public void setSiTraslado(SiTraslado siTraslado) {
        this.siTraslado = siTraslado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODIGO", nullable=false, insertable=false, updatable=false)
    public SiUnidadAcademica getSiUnidadAcademica() {
        return this.siUnidadAcademica;
    }
    
    public void setSiUnidadAcademica(SiUnidadAcademica siUnidadAcademica) {
        this.siUnidadAcademica = siUnidadAcademica;
    }




}


