package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SiSePresta generated by hbm2java
 */
@Entity
@Table(name="SI_SE_PRESTA"
    ,schema="dbo"
    ,catalog="DB_GRUPO4"
)
public class SiSePresta  implements java.io.Serializable {


     private SiSePrestaId id;
     private SiBienInstitucional siBienInstitucional;
     private SiPrestamo siPrestamo;
     private byte[] reporte;
     private String estado;
     private String descripcionEstado;
     private Date fechaFinalReal;

    public SiSePresta() {
    }

	
    public SiSePresta(SiSePrestaId id, SiBienInstitucional siBienInstitucional, SiPrestamo siPrestamo) {
        this.id = id;
        this.siBienInstitucional = siBienInstitucional;
        this.siPrestamo = siPrestamo;
    }
    public SiSePresta(SiSePrestaId id, SiBienInstitucional siBienInstitucional, SiPrestamo siPrestamo, byte[] reporte, String estado, String descripcionEstado, Date fechaFinalReal) {
       this.id = id;
       this.siBienInstitucional = siBienInstitucional;
       this.siPrestamo = siPrestamo;
       this.reporte = reporte;
       this.estado = estado;
       this.descripcionEstado = descripcionEstado;
       this.fechaFinalReal = fechaFinalReal;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="numero", column=@Column(name="NUMERO", nullable=false) ), 
        @AttributeOverride(name="anno", column=@Column(name="ANNO", nullable=false) ), 
        @AttributeOverride(name="consecutivo", column=@Column(name="CONSECUTIVO", nullable=false) ) } )
    public SiSePrestaId getId() {
        return this.id;
    }
    
    public void setId(SiSePrestaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONSECUTIVO", nullable=false, insertable=false, updatable=false)
    public SiBienInstitucional getSiBienInstitucional() {
        return this.siBienInstitucional;
    }
    
    public void setSiBienInstitucional(SiBienInstitucional siBienInstitucional) {
        this.siBienInstitucional = siBienInstitucional;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="NUMERO", referencedColumnName="NUMERO", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ANNO", referencedColumnName="ANNO", nullable=false, insertable=false, updatable=false) } )
    public SiPrestamo getSiPrestamo() {
        return this.siPrestamo;
    }
    
    public void setSiPrestamo(SiPrestamo siPrestamo) {
        this.siPrestamo = siPrestamo;
    }

    
    @Column(name="REPORTE")
    public byte[] getReporte() {
        return this.reporte;
    }
    
    public void setReporte(byte[] reporte) {
        this.reporte = reporte;
    }

    
    @Column(name="ESTADO", length=15)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="DESCRIPCION_ESTADO", length=150)
    public String getDescripcionEstado() {
        return this.descripcionEstado;
    }
    
    public void setDescripcionEstado(String descripcionEstado) {
        this.descripcionEstado = descripcionEstado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_FINAL_REAL", length=10)
    public Date getFechaFinalReal() {
        return this.fechaFinalReal;
    }
    
    public void setFechaFinalReal(Date fechaFinalReal) {
        this.fechaFinalReal = fechaFinalReal;
    }




}


