package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SiSolicitudDesecho generated by hbm2java
 */
@Entity
@Table(name="SI_SOLICITUD_DESECHO"
    ,schema="dbo"
    ,catalog="DB_GRUPO4"
)
public class SiSolicitudDesecho  implements java.io.Serializable {


     private SiSolicitudDesechoId id;
     private SiBienInstitucional siBienInstitucional;
     private SiDesecho siDesecho;
     private Set<SiSubinformeDesecho> siSubinformeDesechos = new HashSet<SiSubinformeDesecho>(0);

    public SiSolicitudDesecho() {
    }

	
    public SiSolicitudDesecho(SiSolicitudDesechoId id, SiBienInstitucional siBienInstitucional, SiDesecho siDesecho) {
        this.id = id;
        this.siBienInstitucional = siBienInstitucional;
        this.siDesecho = siDesecho;
    }
    public SiSolicitudDesecho(SiSolicitudDesechoId id, SiBienInstitucional siBienInstitucional, SiDesecho siDesecho, Set<SiSubinformeDesecho> siSubinformeDesechos) {
       this.id = id;
       this.siBienInstitucional = siBienInstitucional;
       this.siDesecho = siDesecho;
       this.siSubinformeDesechos = siSubinformeDesechos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="numero", column=@Column(name="NUMERO", nullable=false) ), 
        @AttributeOverride(name="anno", column=@Column(name="ANNO", nullable=false) ) } )
    public SiSolicitudDesechoId getId() {
        return this.id;
    }
    
    public void setId(SiSolicitudDesechoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONSECUTIVO", nullable=false)
    public SiBienInstitucional getSiBienInstitucional() {
        return this.siBienInstitucional;
    }
    
    public void setSiBienInstitucional(SiBienInstitucional siBienInstitucional) {
        this.siBienInstitucional = siBienInstitucional;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="NUMERO_DESECHO", referencedColumnName="NUMERO", nullable=false), 
        @JoinColumn(name="ANNO_DESECHO", referencedColumnName="ANNO", nullable=false) } )
    public SiDesecho getSiDesecho() {
        return this.siDesecho;
    }
    
    public void setSiDesecho(SiDesecho siDesecho) {
        this.siDesecho = siDesecho;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="siSolicitudDesecho")
    public Set<SiSubinformeDesecho> getSiSubinformeDesechos() {
        return this.siSubinformeDesechos;
    }
    
    public void setSiSubinformeDesechos(Set<SiSubinformeDesecho> siSubinformeDesechos) {
        this.siSubinformeDesechos = siSubinformeDesechos;
    }




}


