package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SiSubinformeDesechoId generated by hbm2java
 */
@Embeddable
public class SiSubinformeDesechoId  implements java.io.Serializable {


     private int numeroInforme;
     private int annoInforme;
     private String codigoInforme;

    public SiSubinformeDesechoId() {
    }

    public SiSubinformeDesechoId(int numeroInforme, int annoInforme, String codigoInforme) {
       this.numeroInforme = numeroInforme;
       this.annoInforme = annoInforme;
       this.codigoInforme = codigoInforme;
    }
   


    @Column(name="NUMERO_INFORME", nullable=false)
    public int getNumeroInforme() {
        return this.numeroInforme;
    }
    
    public void setNumeroInforme(int numeroInforme) {
        this.numeroInforme = numeroInforme;
    }


    @Column(name="ANNO_INFORME", nullable=false)
    public int getAnnoInforme() {
        return this.annoInforme;
    }
    
    public void setAnnoInforme(int annoInforme) {
        this.annoInforme = annoInforme;
    }


    @Column(name="CODIGO_INFORME", nullable=false, length=20)
    public String getCodigoInforme() {
        return this.codigoInforme;
    }
    
    public void setCodigoInforme(String codigoInforme) {
        this.codigoInforme = codigoInforme;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SiSubinformeDesechoId) ) return false;
		 SiSubinformeDesechoId castOther = ( SiSubinformeDesechoId ) other; 
         
		 return (this.getNumeroInforme()==castOther.getNumeroInforme())
 && (this.getAnnoInforme()==castOther.getAnnoInforme())
 && ( (this.getCodigoInforme()==castOther.getCodigoInforme()) || ( this.getCodigoInforme()!=null && castOther.getCodigoInforme()!=null && this.getCodigoInforme().equals(castOther.getCodigoInforme()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNumeroInforme();
         result = 37 * result + this.getAnnoInforme();
         result = 37 * result + ( getCodigoInforme() == null ? 0 : this.getCodigoInforme().hashCode() );
         return result;
   }   


}


