package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SiSubinformeDesecho generated by hbm2java
 */
@Entity
@Table(name="SI_SUBINFORME_DESECHO"
    ,schema="dbo"
    ,catalog="DB_GRUPO4"
)
public class SiSubinformeDesecho  implements java.io.Serializable {


     private SiSubinformeDesechoId id;
     private SiActaDesecho siActaDesecho;
     private SiInformeTecnico siInformeTecnico;
     private SiSolicitudDesecho siSolicitudDesecho;
     private SiUnidadEvaluadora siUnidadEvaluadora;
     private String motivoResultado;
     private String resultado;

    public SiSubinformeDesecho() {
    }

	
    public SiSubinformeDesecho(SiSubinformeDesechoId id, SiInformeTecnico siInformeTecnico, SiSolicitudDesecho siSolicitudDesecho, SiUnidadEvaluadora siUnidadEvaluadora, String motivoResultado, String resultado) {
        this.id = id;
        this.siInformeTecnico = siInformeTecnico;
        this.siSolicitudDesecho = siSolicitudDesecho;
        this.siUnidadEvaluadora = siUnidadEvaluadora;
        this.motivoResultado = motivoResultado;
        this.resultado = resultado;
    }
    public SiSubinformeDesecho(SiSubinformeDesechoId id, SiActaDesecho siActaDesecho, SiInformeTecnico siInformeTecnico, SiSolicitudDesecho siSolicitudDesecho, SiUnidadEvaluadora siUnidadEvaluadora, String motivoResultado, String resultado) {
       this.id = id;
       this.siActaDesecho = siActaDesecho;
       this.siInformeTecnico = siInformeTecnico;
       this.siSolicitudDesecho = siSolicitudDesecho;
       this.siUnidadEvaluadora = siUnidadEvaluadora;
       this.motivoResultado = motivoResultado;
       this.resultado = resultado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="numeroInforme", column=@Column(name="NUMERO_INFORME", nullable=false) ), 
        @AttributeOverride(name="annoInforme", column=@Column(name="ANNO_INFORME", nullable=false) ), 
        @AttributeOverride(name="codigoInforme", column=@Column(name="CODIGO_INFORME", nullable=false, length=20) ) } )
    public SiSubinformeDesechoId getId() {
        return this.id;
    }
    
    public void setId(SiSubinformeDesechoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="NUMERO_ACTA", referencedColumnName="NUMERO"), 
        @JoinColumn(name="ANNO_ACTA", referencedColumnName="ANNO"), 
        @JoinColumn(name="OFICIO_DESECHO", referencedColumnName="OFICIO_DESECHO") } )
    public SiActaDesecho getSiActaDesecho() {
        return this.siActaDesecho;
    }
    
    public void setSiActaDesecho(SiActaDesecho siActaDesecho) {
        this.siActaDesecho = siActaDesecho;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="NUMERO_INFORME", referencedColumnName="NUMERO_INFORME", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ANNO_INFORME", referencedColumnName="ANNO_INFORME", nullable=false, insertable=false, updatable=false) } )
    public SiInformeTecnico getSiInformeTecnico() {
        return this.siInformeTecnico;
    }
    
    public void setSiInformeTecnico(SiInformeTecnico siInformeTecnico) {
        this.siInformeTecnico = siInformeTecnico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="NUMERO_SOLICITUD", referencedColumnName="NUMERO", nullable=false), 
        @JoinColumn(name="ANNO_SOLICITUD", referencedColumnName="ANNO", nullable=false) } )
    public SiSolicitudDesecho getSiSolicitudDesecho() {
        return this.siSolicitudDesecho;
    }
    
    public void setSiSolicitudDesecho(SiSolicitudDesecho siSolicitudDesecho) {
        this.siSolicitudDesecho = siSolicitudDesecho;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODIGO_EVALUADORA", nullable=false)
    public SiUnidadEvaluadora getSiUnidadEvaluadora() {
        return this.siUnidadEvaluadora;
    }
    
    public void setSiUnidadEvaluadora(SiUnidadEvaluadora siUnidadEvaluadora) {
        this.siUnidadEvaluadora = siUnidadEvaluadora;
    }

    
    @Column(name="MOTIVO_RESULTADO", nullable=false, length=300)
    public String getMotivoResultado() {
        return this.motivoResultado;
    }
    
    public void setMotivoResultado(String motivoResultado) {
        this.motivoResultado = motivoResultado;
    }

    
    @Column(name="RESULTADO", nullable=false, length=20)
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }




}


