package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SiTraslado generated by hbm2java
 */
@Entity
@Table(name="SI_TRASLADO"
    ,schema="dbo"
    ,catalog="DB_GRUPO4"
)
public class SiTraslado  implements java.io.Serializable {


     private SiTrasladoId id;
     private SiPersona siPersona;
     private String numeroOficio;
     private byte[] reporte;
     private String observaciones;
     private String estado;
     private Date fechaTraslado;
     private Set<SiSeTraslada> siSeTrasladas = new HashSet<SiSeTraslada>(0);

    public SiTraslado() {
    }

	
    public SiTraslado(SiTrasladoId id, SiPersona siPersona, String numeroOficio) {
        this.id = id;
        this.siPersona = siPersona;
        this.numeroOficio = numeroOficio;
    }
    public SiTraslado(SiTrasladoId id, SiPersona siPersona, String numeroOficio, byte[] reporte, String observaciones, String estado, Date fechaTraslado, Set<SiSeTraslada> siSeTrasladas) {
       this.id = id;
       this.siPersona = siPersona;
       this.numeroOficio = numeroOficio;
       this.reporte = reporte;
       this.observaciones = observaciones;
       this.estado = estado;
       this.fechaTraslado = fechaTraslado;
       this.siSeTrasladas = siSeTrasladas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="numero", column=@Column(name="NUMERO", nullable=false) ), 
        @AttributeOverride(name="anno", column=@Column(name="ANNO", nullable=false) ) } )
    public SiTrasladoId getId() {
        return this.id;
    }
    
    public void setId(SiTrasladoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CEDULA", nullable=false)
    public SiPersona getSiPersona() {
        return this.siPersona;
    }
    
    public void setSiPersona(SiPersona siPersona) {
        this.siPersona = siPersona;
    }
    
    @Column(name="NUMERO_OFICIO", nullable=false, length=30)
    public String getNumeroOficio() {
        return this.numeroOficio;
    }
    
    public void setNumeroOficio(String numeroOficio) {
        this.numeroOficio = numeroOficio;
    }

    
    @Column(name="REPORTE")
    public byte[] getReporte() {
        return this.reporte;
    }
    
    public void setReporte(byte[] reporte) {
        this.reporte = reporte;
    }

    
    @Column(name="OBSERVACIONES", length=300)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    
    @Column(name="ESTADO", length=15)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_TRASLADO", length=10)
    public Date getFechaTraslado() {
        return this.fechaTraslado;
    }
    
    public void setFechaTraslado(Date fechaTraslado) {
        this.fechaTraslado = fechaTraslado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="siTraslado")
    public Set<SiSeTraslada> getSiSeTrasladas() {
        return this.siSeTrasladas;
    }
    
    public void setSiSeTrasladas(Set<SiSeTraslada> siSeTrasladas) {
        this.siSeTrasladas = siSeTrasladas;
    }




}


