package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SiUnidadEvaluadora generated by hbm2java
 */
@Entity
@Table(name="SI_UNIDAD_EVALUADORA"
    ,schema="dbo"
    ,catalog="DB_GRUPO4"
    , uniqueConstraints = @UniqueConstraint(columnNames="NOMBRE") 
)
public class SiUnidadEvaluadora  implements java.io.Serializable {


     private String codigo;
     private SiPersona siPersona;
     private String nombre;
     private Set<SiSubinformeDesecho> siSubinformeDesechos = new HashSet<SiSubinformeDesecho>(0);

    public SiUnidadEvaluadora() {
    }

	
    public SiUnidadEvaluadora(String codigo, SiPersona siPersona, String nombre) {
        this.codigo = codigo;
        this.siPersona = siPersona;
        this.nombre = nombre;
    }
    public SiUnidadEvaluadora(String codigo, SiPersona siPersona, String nombre, Set<SiSubinformeDesecho> siSubinformeDesechos) {
       this.codigo = codigo;
       this.siPersona = siPersona;
       this.nombre = nombre;
       this.siSubinformeDesechos = siSubinformeDesechos;
    }
   
     @Id 

    
    @Column(name="CODIGO", unique=true, nullable=false, length=20)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CEDULA", nullable=false)
    public SiPersona getSiPersona() {
        return this.siPersona;
    }
    
    public void setSiPersona(SiPersona siPersona) {
        this.siPersona = siPersona;
    }

    
    @Column(name="NOMBRE", unique=true, nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="siUnidadEvaluadora")
    public Set<SiSubinformeDesecho> getSiSubinformeDesechos() {
        return this.siSubinformeDesechos;
    }
    
    public void setSiSubinformeDesechos(Set<SiSubinformeDesecho> siSubinformeDesechos) {
        this.siSubinformeDesechos = siSubinformeDesechos;
    }




}


