package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SiUnidadAcademica generated by hbm2java
 */
@Entity
@Table(name = "SI_UNIDAD_ACADEMICA",
         schema = "dbo",
         catalog = "DB_GRUPO4",
         uniqueConstraints = @UniqueConstraint(columnNames = "NOMBRE")
)
public class SiUnidadAcademica implements java.io.Serializable {

    private String codigo;
    private String nombre;
    private Set<SiBienInstitucional> siBienInstitucionals = new HashSet<SiBienInstitucional>(0);
    private Set<SiAdquisicionPorTraslado> siAdquisicionPorTraslados = new HashSet<SiAdquisicionPorTraslado>(0);
    private Set<SiSeTraslada> siSeTrasladas = new HashSet<SiSeTraslada>(0);

    public SiUnidadAcademica() {
    }

    public SiUnidadAcademica(String codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }

    public SiUnidadAcademica(String codigo, String nombre, Set<SiBienInstitucional> siBienInstitucionals, Set<SiAdquisicionPorTraslado> siAdquisicionPorTraslados, Set<SiSeTraslada> siSeTrasladas) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.siBienInstitucionals = siBienInstitucionals;
        this.siAdquisicionPorTraslados = siAdquisicionPorTraslados;
        this.siSeTrasladas = siSeTrasladas;
    }

    @Id

    @Column(name = "CODIGO", unique = true, nullable = false, length = 20)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "NOMBRE", unique = true, nullable = false, length = 100)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "siUnidadAcademica")
    public Set<SiBienInstitucional> getSiBienInstitucionals() {
        return this.siBienInstitucionals;
    }

    public void setSiBienInstitucionals(Set<SiBienInstitucional> siBienInstitucionals) {
        this.siBienInstitucionals = siBienInstitucionals;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "siUnidadAcademica")
    public Set<SiAdquisicionPorTraslado> getSiAdquisicionPorTraslados() {
        return this.siAdquisicionPorTraslados;
    }

    public void setSiAdquisicionPorTraslados(Set<SiAdquisicionPorTraslado> siAdquisicionPorTraslados) {
        this.siAdquisicionPorTraslados = siAdquisicionPorTraslados;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "siUnidadAcademica")
    public Set<SiSeTraslada> getSiSeTrasladas() {
        return this.siSeTrasladas;
    }

    public void setSiSeTrasladas(Set<SiSeTraslada> siSeTrasladas) {
        this.siSeTrasladas = siSeTrasladas;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (codigo != null ? codigo.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        if (!(object instanceof SiUnidadAcademica)) {
            return false;
        }
        SiUnidadAcademica other = (SiUnidadAcademica) object;
        if ((this.codigo == null && other.codigo != null) || (this.codigo != null && !this.codigo.equals(other.codigo))) {
            return false;
        }
        return true;
    }

}
