package cr.ac.ucr.inie.sigepro.persistencia.entidad;
// Generated 21/06/2017 02:16:07 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SiUsuario generated by hbm2java
 */
@Entity
@Table(name="SI_USUARIO"
    ,schema="dbo"
    ,catalog="DB_GRUPO4"
)
public class SiUsuario  implements java.io.Serializable {


     private String nombreUsuario;
     private String contrasenna;
     private String rol;

    public SiUsuario() {
    }

    public SiUsuario(String nombreUsuario, String contrasenna, String rol) {
       this.nombreUsuario = nombreUsuario;
       this.contrasenna = contrasenna;
       this.rol = rol;
    }
   
     @Id 

    
    @Column(name="NOMBRE_USUARIO", unique=true, nullable=false, length=30)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    
    @Column(name="CONTRASENNA", nullable=false, length=40)
    public String getContrasenna() {
        return this.contrasenna;
    }
    
    public void setContrasenna(String contrasenna) {
        this.contrasenna = contrasenna;
    }

    
    @Column(name="ROL", nullable=false, length=20)
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }




}


